version: '3.1'
services:
  stats-server:
    build: ewm-stats
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - POSTGRES_URL=jdbc:postgresql://stats-db:5432/ewm_stats
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-service-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_stats
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass

  ewm-service:
    build: ewm-main
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - POSTGRES_URL=jdbc:postgresql://ewm-db:5432/ewm_main
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-main-service-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_main
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
